### PR TITLE
Apply latest changes from `datalad-catalog`

### LINKED ISSUE #10: BUG: subdataset filtering not working
With the current site in production, I get the following when starting to type in the search field:

```
vue.js:634 [Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'toLowerCase')"

found in

---> <Anonymous>
       <Root>
warn @ vue.js:634
logError @ vue.js:1902
globalHandleError @ vue.js:1897
handleError @ vue.js:1857
Vue._render @ vue.js:3574
updateComponent @ vue.js:4082
get @ vue.js:4494
run @ vue.js:4569
flushSchedulerQueue @ vue.js:4327
(anonymous) @ vue.js:1998
flushCallbacks @ vue.js:1924
Promise.then (async)
timerFunc @ vue.js:1951
nextTick @ vue.js:2008
queueWatcher @ vue.js:4419
update @ vue.js:4559
notify @ vue.js:745
reactiveSetter @ vue.js:1070
proxySetter @ vue.js:4643
onInput @ bootstrap-vue.2.21.2.min.js:10
invokeWithErrorHandling @ vue.js:1872
invoker @ vue.js:2197
original._wrapper @ vue.js:7591
vue.js:1906 TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at app_component_dataset.js:217:28
    at Array.some (<anonymous>)
    at app_component_dataset.js:215:27
    at Array.filter (<anonymous>)
    at VueComponent.filteredSubdatasets (app_component_dataset.js:208:36)
    at Watcher.get (vue.js:4494:27)
    at Watcher.evaluate (vue.js:4596:23)
    at VueComponent.computedGetter [as filteredSubdatasets] (vue.js:4847:19)
    at VueComponent.tagFilteredSubdatasets (app_component_dataset.js:223:32)
    at Watcher.get (vue.js:4494:27)
```

### LINKED ISSUE #31: Sizing issue with dataset buttons
image

Minor, but still worth fixing.

### LINKED ISSUE #38: Twitter is dead
image

Maybe say X (Twitter) -- or something along these lines.

### LINKED ISSUE #39: Misleading click-action-promise in content tab
image

Each name in the content listing shown above is "clickable" (as indicated by a change in the cursor on hover). But only for directories clicking results in any action (expand directory subtree).

Downloadable files have a small "cloud" symbol in their row on the right.

It would make sense to me to duplicate the hyperlink for downloading a file with the actual file name as the anchor. This would give some files an actual click actions. Users may expect filenames to functions as download links from other content listings (e.g., standard apache functionality).

The cloud symbol could stay as it, or be demoted to an indicator symbol only.

### LINKED ISSUE #43: Not all urls should be https by default
Z02 sub-datasets files were reported (in tabby files sent to me) with [UNC](https://en.wikipedia.org/wiki/Path_(computing)#Universal_Naming_Convention) paths in place of URL. AFAIK these were not altered by my metadata extraction. These paths / URLs start with `//uk-koeln.lolal/daten/...`. It looks like catalog code adds "https:" in front when displaying the download button.

(independent of that is the fact that the UNC paths reported in tabby were malformed to begin with - part of the path is duplicated)

### LINKED ISSUE #45: Mention that (sub)dataset filtering is only for immediate subdatasets
I think this is very useful functionality for the SFB superdataset, but becomes increasingly pointless towards leaf-datasets, or with dataset that have few subdatasets.

This may lead to the expectation that "filtering" is actually "searching", and result in frustration when there are no hits.

Personally, I find that the term "filtering" already communicate the scope clearly. But maybe we can tweak the UX a bit more. For example:

https://psychoinformatics-de.github.io/sfb1451-projects-catalog/#/dataset/ee671e31-3c6e-4d83-952a-cfc66c84390e/268104da80180112470f7fbd377d154dcb2cac4c

only has a single subdataset, and we offer "filtering". Maybe we should increase the threshold to `>3`?

### PR DESCRIPTION
**Pull request by jsheunis**
Demo of the changes available here: https://jsheunis.github.io/sfb1451-projects-catalog/

This PR applies a range of commits from the current version of `datalad-catalog` to this repository, specifically addressing the issues below:
- closes https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/10
- closes https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/31
- partly addresses https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/33
- addresses one aspect of https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/34
- closes https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/38
- closes https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/39
- closes https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/43
- closes https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/45

More specific information about the changes is available in the `datalad-catalog` PRs:
- https://github.com/datalad/datalad-catalog/pull/350
- https://github.com/datalad/datalad-catalog/pull/358
- https://github.com/datalad/datalad-catalog/pull/366
- https://github.com/datalad/datalad-catalog/pull/367
- https://github.com/datalad/datalad-catalog/pull/368
- https://github.com/datalad/datalad-catalog/pull/369
- https://github.com/datalad/datalad-catalog/pull/373

### CODE REVIEW

**Comment by jsheunis** [comment]
I see the border around the dataset title does not display nicely for titles that span multiple lines. will update this.

**Comment by jsheunis** [comment]
> I see the border around the dataset title does not display nicely for titles that span multiple lines. will update this.

Updated

**Review by adswa — COMMENTED** [review]
I have explored your rendered demo using Firefox 102.7.0esr (64-bit), and I went through every linked issue. Overall, it looks like the linked issues are indeed fixed by all these changes, I just had two observations noted below:

For issue https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/33, I confirmed that I can link the funding tab (e.g., https://jsheunis.github.io/sfb1451-projects-catalog/#/dataset/9964001a-5e8c-5c70-aedb-55141cca07c0/latest/funding, which leads to "funding"), but this doesn't seem to work for the "SFB1451" tab:
https://jsheunis.github.io/sfb1451-projects-catalog/#/dataset/9964001a-5e8c-5c70-aedb-55141cca07c0/latest/SFB1451 (this links to subdatasets).

For issue https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/43 I did not find non-https urls, likely because I don't know where to look or because non https urls aren't hyperlinks anymore due to https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/39?

**Comment by jsheunis** [comment]
Thanks @adswa!

> For issue https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/33, I confirmed that I can link the funding tab (e.g., https://jsheunis.github.io/sfb1451-projects-catalog/#/dataset/9964001a-5e8c-5c70-aedb-55141cca07c0/latest/funding, which leads to "funding"), but this doesn't seem to work for the "SFB1451" tab:
https://jsheunis.github.io/sfb1451-projects-catalog/#/dataset/9964001a-5e8c-5c70-aedb-55141cca07c0/latest/SFB1451 (this links to subdatasets).

Indeed, this is the same for me. Thanks for spotting this, I will look into it.

> For issue https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/43 I did not find non-https urls, likely because I don't know where to look or because non https urls aren't hyperlinks anymore due to https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/39?

Yup I already "eliminated" the non-http urls via https://github.com/datalad/datalad-catalog/commit/498c2787ebb78c618f32e0857255d0455e43a20e. You can see the previous state in the current production site: https://psychoinformatics-de.github.io/sfb1451-projects-catalog/

**Comment by jsheunis** [comment]
> For issue https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/33, I confirmed that I can link the funding tab (e.g., https://jsheunis.github.io/sfb1451-projects-catalog/#/dataset/9964001a-5e8c-5c70-aedb-55141cca07c0/latest/funding, which leads to "funding"), but this doesn't seem to work for the "SFB1451" tab:
https://jsheunis.github.io/sfb1451-projects-catalog/#/dataset/9964001a-5e8c-5c70-aedb-55141cca07c0/latest/SFB1451 (this links to subdatasets).

Looks like a simple capitalisation issue. The `tab_param` here https://github.com/datalad/datalad-catalog/blob/main/datalad_catalog/catalog/assets/app_component_dataset.js#L514 needs to be changed to `tab_param.toLowerCase()`

**Comment by mslw** [comment]
Thanks for the review @adswa , and naturally thanks for the rapid-fire changes @jsheunis !

I also played with the demo - I think especially the "back" button and improved filtering make it feel decidedly snappier.

I understand that this is ready to merge? If so, I will do it later today, but I wanted to push one more metadata update first.

There is one minor thing:

> > For issue #43 I did not find non-https urls, likely because I don't know where to look or because non https urls aren't hyperlinks anymore due to #39?
> 
> Yup I already "eliminated" the non-http urls via [datalad/datalad-catalog@498c278](https://github.com/datalad/datalad-catalog/commit/498c2787ebb78c618f32e0857255d0455e43a20e). You can see the previous state in the current production site: https://psychoinformatics-de.github.io/sfb1451-projects-catalog/

which I feel was a bit "throwing the baby out with the bathwater" - I've already suggested in #43 that instead of requiring `urlparse(url).scheme in ("http", "https")` (sorry for using Python examples when talking about JS...) to showing download button, my instinct would be to just say `urlparse(url).scheme != ""`, but I don't want to override the change with another hasty change. In any case, that's not a blocker for me, and from my memory I'm not sure if we have any useful non-html links in the SFB metadata right now...

edit: corrected from "netloc" to "scheme", and "html" to "http" to avoid future confusion

**Comment by jsheunis** [comment]
> I understand that this is ready to merge?

I want to push a couple of changes still, including a fix for the first issue that @adswa highlighted. @mslw I will tag you here when done.

Wrt your second point, I agree the current state is a somewhat blunt "fix". I do think the UX is important though, and having a download button that always fails is bad UX. I would suggest more fit-for-purpose functionality, such as having a scheme for interpretation and having different renderings and UX accordingly. I think this can probably be explored further in a separate `datalad-catalog` issue, though, and then an eventual fix can be merged in here separately if/when it is addressed. WDYT?

**Comment by mslw** [comment]
> Wrt your second point, I agree the current state is a somewhat blunt "fix". I do think the UX is important though, and having a download button that always fails is bad UX. I would suggest more fit-for-purpose functionality, such as having a scheme for interpretation and having different renderings and UX accordingly. I think this can probably be explored further in a separate `datalad-catalog` issue, though, and then an eventual fix can be merged in here separately if/when it is addressed. WDYT?

Yes, absolutely.

**Comment by jsheunis** [comment]
I missed this issue previously: https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/22. Will work this into the PR as well.

**Comment by tmheunis** [comment]
I have reviewed the issues in this PR, and have also done some other spot checks. For issues applicable to both the sfb-catalog and datalad-catalog I have created specific issues in the datalad-catalog repository and listed them below in number 3.

### 1. Download link available for inaccessible files
In the dataset, https://jsheunis.github.io/sfb1451-projects-catalog/#/dataset/9964001a-5e8c-5c70-aedb-55141cca07c0/latest, click on content tab and then go to any of the files under Z03. For e.g. if you click on P000840, https://data.inm-icf.de/Z03/P000840_dicom.tar, this file cannot be accessed. Should this then display as a downloadable file? This issue in datalad-catalog seems to be related https://github.com/datalad/datalad-catalog/issues/380, but the question still remains what needs to be done for the SFB catalog specifically?

### 2. URL based tab navigation still incomplete
E.g. If I click on 'funding' and copy the url it does not include the tab parameter in the url. The same applies for the 'content' tab. If I do include the 'funding' tab parameter in the url it correctly opens that tab, but if I then click on 'content', for instance, the url still displays 'funding'. The url should end with 'content' if I am on the 'content' tab, and end on 'funding' if I am on the 'funding' tab. Link issue https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/33. 

### 3. Other issues created on datalad-catalog, applicable here too
 
https://github.com/datalad/datalad-catalog/issues/383
https://github.com/datalad/datalad-catalog/issues/384
https://github.com/datalad/datalad-catalog/issues/385
https://github.com/datalad/datalad-catalog/issues/386
https://github.com/datalad/datalad-catalog/issues/387
https://github.com/datalad/datalad-catalog/issues/388
https://github.com/datalad/datalad-catalog/issues/389
https://github.com/datalad/datalad-catalog/issues/390

**Comment by mslw** [comment]
Thanks @tmheunis ! I can speak to one question directly:

> ### 1. Download link available for inaccessible files
> 
> In the dataset, https://jsheunis.github.io/sfb1451-projects-catalog/#/dataset/9964001a-5e8c-5c70-aedb-55141cca07c0/latest, click on content tab and then go to any of the files under Z03. For e.g. if you click on P000840, https://data.inm-icf.de/Z03/P000840_dicom.tar, this file cannot be accessed. Should this then display as a downloadable file? This issue in datalad-catalog seems to be related [datalad/datalad-catalog#380](https://github.com/datalad/datalad-catalog/issues/380), but the question still remains what needs to be done for the SFB catalog specifically?

The source for these URLs is a tabby file with dataset description prepared by the Z03 project members. In particular, the urls are accessible only within FZJ internal network and require additional authentication. Personally, I think the links should be displayed, if only as an information.

**Comment by jsheunis** [comment]
Thanks for the review and all the catalog issues, @tmheunis!

Some comments after my latest commits:

> For issue https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/33, I confirmed that I can link the funding tab (e.g., https://jsheunis.github.io/sfb1451-projects-catalog/#/dataset/9964001a-5e8c-5c70-aedb-55141cca07c0/latest/funding, which leads to "funding"), but this doesn't seem to work for the "SFB1451" tab:
https://jsheunis.github.io/sfb1451-projects-catalog/#/dataset/9964001a-5e8c-5c70-aedb-55141cca07c0/latest/SFB1451 (this links to subdatasets).

The capitalization issue that @adswa pointed out is now fixed and included in this PR.

@mslw @tmheunis, regarding:

> The source for these URLs is a tabby file with dataset description prepared by the Z03 project members. In particular, the urls are accessible only within FZJ internal network and require additional authentication. Personally, I think the links should be displayed, if only as an information.

I'm also fine with this approach for the current goal, and then to use https://github.com/datalad/datalad-catalog/issues/380 to figure the challenge out for the longer term.

@tmheunis, re:

> ### 2. URL based tab navigation still incomplete
> E.g. If I click on 'funding' and copy the url it does not include the tab parameter in the url. The same applies for the 'content' tab. If I do include the 'funding' tab parameter in the url it correctly opens that tab, but if I then click on 'content', for instance, the url still displays 'funding'. The url should end with 'content' if I am on the 'content' tab, and end on 'funding' if I am on the 'funding' tab. Link issue https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/33.

Good point, I agree. I have updated this PR description at the top to indicate that the PR does not fully close #33, and I have created this issue in `datalad-catalog` to address the remaining problem: https://github.com/datalad/datalad-catalog/issues/391

@mslw regarding:

> I missed this issue previously: https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/22. Will work this into the PR as well.

as you saw in the linked issue there is a screenshot of a proposed solution. Once we get consensus on the styling, that can also become a separate PR, i.e. it does not necessarily have to be incorporated into this one.

I believe all other issues that became relevant in the course of this PR review process have now received their own tracking issues, either in this repo or in `datalad-catalog`. So I think if you are happy with the current state @mslw, you are welcome to merge. Fixes for the issues that remain open here, and any further changes in datalad-catalog, can then become part of a new PR.

**Comment by mslw** [comment]
Thank you again @jsheunis this is a lot of improvements!

Given the green light in your latest comments, and reassured by the fact that more people looked into it, I'm merging. Thx all!

**Pull request merged**
